spring.application.name=springboot_module4

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://DESKTOP-B8F9BM9\\SQLEXPRESS;databaseName=module_4;encrypt=false;trustServerCertificate=true
spring.datasource.username=prabhat
spring.datasource.password=Penguin@5698

# we observed that in this connection string, since sql-server is the database server and SQLEXPRESS being the instance,
#since a single host can have many instances( this is just the name). -> and then database -> properties while connecting.
# also keep in mind tht sometimes when spring starter parent is handlig the dependencies, you do not need to explicitely mention the
# version of jdbc-driver spring needs to load in order to talk to database server

spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.show-sql=true
# this might be for shoeing all the sql running behind

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.defer-datasource-initialization=true

#it makes the application first create all the tables followed by executing the sql scripts


#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
# to execute the script from here








